<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Project Introduction" data-toc-modified-id="Project Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Project Introduction</a></span></li><li><span><a href="#1.-import" data-toc-modified-id="1.-import-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>1. import</a></span></li><li><span><a href="#2.Pandasdataprocessing" data-toc-modified-id="2.Pandasdataprocessing-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>2.Pandasdataprocessing</a></span><ul class="toc-item"><li><span><a href="#2.1-Read Data" data-toc-modified-id="2.1-Read Data-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>2.1 Read Data</a></span></li><li><span><a href="#2.2-view、data and info" data-toc-modified-id="2.2-view、data and info-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>2.2 view、data and info</a></span></li><li><span><a href="#2.3-view" data-toc-modified-id="2.3-view-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>2.3 view</a></span></li><li><span><a href="#2.4-view0" data-toc-modified-id="2.4-view0-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>2.4 view0</a></span></li><li><span><a href="#2.5-0data" data-toc-modified-id="2.5-0data-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>2.5 0data</a></span></li><li><span><a href="#2.6-null" data-toc-modified-id="2.6-null-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>2.6 null</a></span></li><li><span><a href="#2.7-missing values‘’" data-toc-modified-id="2.7-missing values‘’-3.7"><span class="toc-item-num">3.7&nbsp;&nbsp;</span>2.7 missing values‘’</a></span></li><li><span><a href="#2.8-missing values‘’" data-toc-modified-id="2.8-missing values‘’-3.8"><span class="toc-item-num">3.8&nbsp;&nbsp;</span>2.8 missing values‘’</a></span></li><li><span><a href="#2.9-" data-toc-modified-id="2.9--3.9"><span class="toc-item-num">3.9&nbsp;&nbsp;</span>2.9 </a></span></li></ul></li><li><span><a href="#3.-PyechartsData Visualization" data-toc-modified-id="3.-PyechartsData Visualization-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>3. PyechartsData Visualization</a></span><ul class="toc-item"><li><span><a href="#3.1-20Attractiondata" data-toc-modified-id="3.1-20Attractiondata-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>3.1 20Attractiondata</a></span></li><li><span><a href="#3.2-dataNationalDistribution" data-toc-modified-id="3.2-dataNationalDistribution-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>3.2 dataNationalDistribution</a></span></li><li><span><a href="#3.3-Provincial4A-5ACount" data-toc-modified-id="3.3-Provincial4A-5ACount-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>3.3 Provincial4A-5ACount</a></span></li><li><span><a href="#3.4-Provincial4A-5ACount" data-toc-modified-id="3.4-Provincial4A-5ACount-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>3.4 Provincial4A-5ACount</a></span></li><li><span><a href="#3.5-Provincial4A-5ACount" data-toc-modified-id="3.5-Provincial4A-5ACount-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>3.5 Provincial4A-5ACount</a></span></li><li><span><a href="#3.6-Provincial4A-5ADistribution" data-toc-modified-id="3.6-Provincial4A-5ADistribution-4.6"><span class="toc-item-num">4.6&nbsp;&nbsp;</span>3.6 Provincial4A-5ADistribution</a></span></li><li><span><a href="#3.7-PriceShare" data-toc-modified-id="3.7-PriceShare-4.7"><span class="toc-item-num">4.7&nbsp;&nbsp;</span>3.7 PriceShare</a></span></li><li><span><a href="#3.8-PriceCount" data-toc-modified-id="3.8-PriceCount-4.8"><span class="toc-item-num">4.8&nbsp;&nbsp;</span>3.8 PriceCount</a></span></li><li><span><a href="#3.9-Attraction" data-toc-modified-id="3.9-Attraction-4.9"><span class="toc-item-num">4.9&nbsp;&nbsp;</span>3.9 Attraction</a></span></li></ul></li><li><span><a href="#Summary" data-toc-modified-id="Summary-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Summary</a></span></li></ul></div>

# Project Introduction

through NationalAttraction，analyzeNationalcompareAttractionDistribution and ，Attractioncompare，Analyze，need to Review。  

- Keywords

pandasdataprocessing、pyechartsVisualization、jiebaminute

# 1. import

In [1]:
import jieba
import pandas as pd 
from collections import Counter
from pyecharts.charts import Line,Pie,Scatter,Bar,Map,Grid
from pyecharts.charts import WordCloud
from pyecharts import options as opts
from pyecharts.globals import ThemeType
from pyecharts.globals import SymbolType
from pyecharts.commons.utils import JsCode

from pyecharts.globals import CurrentConfig, NotebookType,OnlineHostType
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_NOTEBOOK

# 2.Pandasdataprocessing

## 2.1 Read Data

In [2]:
df = pd.read_excel('./TourismAttraction.xlsx')
df.head()

,City,,,Rating,Price,,//,,,,specific
0,,,NaN,0.0,325.0,19459,··,"121.667917,31.149712",,False,310
1,,,4A,0.0,276.5,19406,··,"121.915647,30.917713",|,False,166
2,,,5A,3.6,116.0,6764,··,"121.728112,31.059636",| and,False,178
3,,,4A,3.5,40.0,5353,··,"121.015977,31.107866",NationalyearEducation,False,6888
4,,,5A,3.8,54.0,3966,··,"121.50626,31.245369",，,False,1

## 2.2 view、data and info

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2443 entries, 0 to 2442
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   City      2443 non-null   object
 1         2443 non-null   object
 2         913 non-null    object
 3   Rating      2443 non-null   float64
 4   Price      2443 non-null   float64
 5         2443 non-null   int64
 6   //   2443 non-null   object
 7         2443 non-null   object
 8         2402 non-null   object
 9       2443 non-null   bool
 10  specific     2440 non-null   object
dtypes: bool(1), float64(2), int64(1), object(7)
memory usage: 193.4+ KB

## 2.3 view

In [4]:
df.describe()

                Rating            Price
count  2443.000000   2443.000000   2443.000000
mean      1.683135    151.780929    360.652886
std       2.012527    649.170226   1043.798441
min       0.000000      0.000000      0.000000
25%       0.000000     32.000000     40.000000
50%       0.000000     62.000000     90.000000
75%       3.700000    120.000000    270.000000
max       5.000000  23888.000000  19459.000000

## 2.4 view0

In [5]:
df.loc[df['']==0,:].head()

,City,,,Rating,Price,,//,,,,specific
301,,,NaN,0.0,0.0,0,·,"121.35037883956,24.815040245504",,False,15
302,,,NaN,3.5,0.0,0,·,"121.60445032684,24.162302549393",minute，,True,
303,,,NaN,0.0,0.0,0,·,"121.44124069779,25.171297755773",,True,
304,,,NaN,5.0,0.0,0,·,"121.53013540214,25.093934468272",days、，,True,
305,,,NaN,5.0,0.0,0,·,"121.52694244942,25.076889096728",，，,False,

123。

## 2.5 0data

In [6]:
df = df[df['']!=0] 
df.shape

(2320, 11)

2320data。

## 2.6 null

In [7]:
df.isnull().sum()

City          0
          0
       1407
Rating          0
Price          0
          0
//       0
          0
         37
        0
specific         2
dtype: int64

has 1407null，37null，specific 2null，has null，datacompare。

## 2.7 missing values‘’

In [8]:
df[''].fillna('', inplace=True)
df.isnull().sum()

City        0
        0
        0
Rating        0
Price        0
        0
//     0
        0
       37
      0
specific       2
dtype: int64

## 2.8 missing values‘’

In [9]:
df.fillna('', inplace=True)
df.isnull().sum()

City       0
       0
       0
Rating       0
Price       0
       0
//    0
       0
       0
     0
specific      0
dtype: int64

## 2.9

In [10]:
df.sort_values('', ascending=False).head()

,City,,,Rating,Price,,//,,,,specific
0,,,,0.0,325.0,19459,··,"121.667917,31.149712",,False,310
1,,,4A,0.0,276.5,19406,··,"121.915647,30.917713",|,False,166
211,,,5A,5.0,58.6,15277,··,"116.403347,39.922148",，,False,4
2187,,（）,5A,4.4,120.0,12714,··,"109.266029,34.386024",,False,1.5
474,,,4A,4.0,52.0,9731,··,"104.152603,30.738951",， minute，,False,1375

# 3. PyechartsData Visualization

## 3.1 20Attractiondata

In [11]:
# 
color_js = """new echarts.graphic.LinearGradient(0, 0, 1, 0,
    [{offset: 0, color: '#009ad6'}, {offset: 1, color: '#ed1941'}], false)"""


sort_info = df.sort_values(by='', ascending=True)
b1 = (
    Bar()
    .add_xaxis(list(sort_info[''])[-20:])
    .add_yaxis('Attraction', sort_info[''].values.tolist()[-20:],itemstyle_opts=opts.ItemStyleOpts(color=JsCode(color_js)))
    .reversal_axis()
    .set_global_opts(
        title_opts=opts.TitleOpts(title='Attractiondata'),
        yaxis_opts=opts.AxisOpts(name='Attraction'),
        xaxis_opts=opts.AxisOpts(name=''),
        )
    .set_series_opts(label_opts=opts.LabelOpts(position="right"))

)
# 
g1 = (
    Grid()
        .add(b1, grid_opts=opts.GridOpts(pos_left='20%', pos_right='5%'))  
)
g1.render_notebook()

## 3.2 dataNationalDistribution

In [12]:
dictcode = {'': '',
 'days': 'days',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
 '': '',
'':'',
 '':'',
 '':''}

In [13]:
df_tmp1 = df[['City','']]
df_counts = df_tmp1.groupby('City').sum()
m1 = (
        Map()
        .add('Distribution', [list(z) for z in zip([dictcode[x] for x in df_counts.index.values.tolist() ], df_counts.values.tolist())], 'china')
        .set_global_opts(
        title_opts=opts.TitleOpts(title='dataDistribution'),
        visualmap_opts=opts.VisualMapOpts(max_=100000, is_piecewise=False,range_color=["white", "#fa8072", "#ed1941"]),
        )
    )
m1.render_notebook()

**、、**，yes**、、、、、**compare。  

## 3.3 Provincial4A-5ACount

In [14]:
# 
color_js = """new echarts.graphic.LinearGradient(0, 1, 0, 0,
    [{offset: 0, color: '#009ad6'}, {offset: 1, color: '#ed1941'}], false)""" 

df_tmp2 = df[df[''].isin(['4A', '5A'])]
df_counts = df_tmp2.groupby('City').count()['']
b2 = (
        Bar()
            .add_xaxis(df_counts.index.values.tolist())
            .add_yaxis('4A-5ACount', df_counts.values.tolist(),itemstyle_opts=opts.ItemStyleOpts(color=JsCode(color_js)))
            .set_global_opts(
            title_opts=opts.TitleOpts(title='Provincial4A-5ACount'),
            datazoom_opts=[opts.DataZoomOpts(), opts.DataZoomOpts(type_='inside')],
        )
    )
b2.render_notebook()

## 3.4 Provincial4A-5ACount

In [15]:
df0 = df_counts.copy()
df0.sort_values(ascending=False, inplace=True)
c1 = (
    Pie()
    .add('', [list(z) for z in zip(df0.index.values.tolist(), df0.values.tolist())],
         radius=['30%', '100%'],
         center=['50%', '60%'],
         rosetype='area',
         )
    .set_global_opts(title_opts=opts.TitleOpts(title='AttractionCount'),
                     legend_opts=opts.LegendOpts(is_show=False),
                     toolbox_opts=opts.ToolboxOpts())
    .set_series_opts(label_opts=opts.LabelOpts(is_show=True, position='inside', font_size=12,
                                               formatter='{b}: {c}', font_style='italic',
                                               font_weight='bold', font_family='Microsoft YaHei'
                                               ))
)
c1.render_notebook()

## 3.5 Provincial4A-5ACount

In [15]:
item_style = {'normal': {'shadowColor': '#000000', 
                         'shadowBlur': 20,
                         'shadowOffsetX':5, 
                         'shadowOffsetY':15
                         }
              }
s1 = (
        Scatter()
        .add_xaxis(df_counts.index.values.tolist())
        .add_yaxis('4A-5ACount', df_counts.values.tolist(),symbol_size=50,itemstyle_opts=item_style)
        .set_global_opts(visualmap_opts=opts.VisualMapOpts(is_show=False, 
                                              type_='size',
                                              range_size=[5,50]))
)
s1.render_notebook()

## 3.6 Provincial4A-5ADistribution

In [32]:
df_tmp3 = df[df[''].isin(['4A', '5A'])]
df_counts = df_tmp3.groupby('City').count()['']
m2 = (
    Map()
    .add('4A-5ADistribution', [list(z) for z in zip([dictcode[x] for x in df_counts.index.values.tolist() ], df_counts.values.tolist())], 'china')
    .set_global_opts(
    title_opts=opts.TitleOpts(title='dataDistribution'),
    visualmap_opts=opts.VisualMapOpts(max_=50, is_piecewise=True),
    )
)
m2.render_notebook()

**、、、、**4A、5ACountcompare。  

## 3.7 PriceShare

In [16]:
# PriceShare
price_level = [0, 50, 100, 150, 200, 250, 300, 350, 400, 500]    
label_level = ['0-50', '50-100', '100-150', '150-200', '200-250', '250-300', '300-350', '350-400', '400-500']    
jzmj_cut = pd.cut(df['Price'], price_level, labels=label_level)        
df_price = jzmj_cut.value_counts()
df_price

0-50       888
50-100     725
100-150    278
150-200    184
200-250     62
250-300     59
300-350     20
350-400     19
400-500     13
Name: Price, dtype: int64

In [17]:
p1 = (
    Pie(init_opts=opts.InitOpts(
            width='800px', height='600px',
            )
       )
        .add(
        '',
        [list(z) for z in zip(df_price.index.tolist(), df_price.values.tolist())],
        radius=['20%', '60%'],
        center=['40%', '50%'],
        rosetype='radius',
        label_opts=opts.LabelOpts(is_show=True),
        )    
        .set_global_opts(title_opts=opts.TitleOpts(title='PriceShare',pos_left='33%',pos_top="5%"),
                        legend_opts=opts.LegendOpts(type_='scroll', pos_left="80%",pos_top="25%",orient="vertical")
                        )
        .set_series_opts(label_opts=opts.LabelOpts(formatter='{b}: {c} ({d}%)'),position='outside')
    )
p1.render_notebook()

## 3.8 PriceCount

In [18]:
color_js = """new echarts.graphic.RadialGradient(
                    0.5, 0.5, 1,
                    [{offset: 0,
                      color: '#009ad6'},
                     {offset: 1,
                      color: '#ed1941'}
                      ])"""

s2 = (
        Scatter()
        .add_xaxis(df_price.index.tolist())
        .add_yaxis('Price', df_price.values.tolist(),symbol_size=50,itemstyle_opts=opts.ItemStyleOpts(color=JsCode(color_js))) 
        .set_global_opts(
            yaxis_opts=opts.AxisOpts(name='Count'),
            xaxis_opts=opts.AxisOpts(name='Price()'))
        .set_global_opts(visualmap_opts=opts.VisualMapOpts(is_show=False, 
                                              # through data
                                              type_='size',
                                              # 
                                              range_size=[5,50]))
)
s2.render_notebook()

## 3.9 Attraction

In [19]:
contents = "".join('%s' % i for i in df[''].values.tolist())
contents_list = jieba.cut(contents)
ac = Counter(contents_list)

stopwords = []
with open('./stopwords.txt', "r",encoding='utf-8') as f:  # file
    data = f.read()  # file
    stopwords = data.split('\n')

for i in stopwords:
    del ac[i]
 
w1 = (
    WordCloud()
    .add("", 
         ac.most_common(150), 
         word_size_range=[5, 100], 
         textstyle_opts=opts.TextStyleOpts(font_family="cursive"),
         shape='star')
    .set_global_opts(title_opts=opts.TitleOpts(title="Attraction"))
)
w1.render_notebook()

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\ADMINI~1\AppData\Local\Temp\2\jieba.cache
Loading model cost 1.001 seconds.
Prefix dict has been built successfully.

# Summary  
* 、、，yes、、、、、compare。  
* 、、、、4A、5ACountcompare。  
* Price100，Share70%，yescompare，has 。